// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace TitanicPredictor
{
    public partial class Titanic
    {
        /// <summary>
        /// model input class for Titanic.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Survived")]
            public float Survived { get; set; }

            [ColumnName(@"Pclass")]
            public float Pclass { get; set; }

            [ColumnName(@"Name")]
            public string Name { get; set; }

            [ColumnName(@"Sex")]
            public string Sex { get; set; }

            [ColumnName(@"Age")]
            public float Age { get; set; }

            [ColumnName(@"Siblings/Spouses Aboard")]
            public float Siblings_Spouses_Aboard { get; set; }

            [ColumnName(@"Parents/Children Aboard")]
            public float Parents_Children_Aboard { get; set; }

            [ColumnName(@"Fare")]
            public float Fare { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for Titanic.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName("PredictedLabel")]
            public float Prediction { get; set; }

            public float[] Score { get; set; }
        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("Titanic.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
